install aws-elasticbeanstalk
install brew-cask
install cabal-install
install cscope
install docker
install emacs
install exiftool
install ffmpeg
install flow
install gambit-scheme
install gcc46
install git
install gst-libav
install gst-plugins-good
install gst-python010
install heroku-toolbelt
install imagemagick
install jetty
install leiningen
install libksba
install libyaml
install lynx
install maven
install mit-scheme
install mongodb
install neovim
install node
install nvm
install plt-racket
install postgresql
install python
install reattach-to-user-namespace
install selenium-server-standalone
install tidy
install tmux
install tree
install vim
